### ISSUE TITLE
Version Compatiblity

### ISSUE THREAD

**Issue by weihao** [Phoenix616/InventoryGui#26]
#### Used Version
Latest Version
 
```
[02:26:55 ERROR]: [ACF] Exception in command: ir
[02:26:55 ERROR]: [ACF] java.lang.reflect.InvocationTargetException
[02:26:55 ERROR]: [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02:26:55 ERROR]: [ACF]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02:26:55 ERROR]: [ACF]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02:26:55 ERROR]: [ACF]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[02:26:55 ERROR]: [ACF]         at co.aikar.commands.RegisteredCommand.invoke(RegisteredCommand.java:152)
[02:26:55 ERROR]: [ACF]         at co.aikar.commands.BaseCommand.executeCommand(BaseCommand.java:577)
[02:26:55 ERROR]: [ACF]         at co.aikar.commands.BaseCommand.execute(BaseCommand.java:513)
[02:26:55 ERROR]: [ACF]         at co.aikar.commands.RootCommand.execute(RootCommand.java:99)
[02:26:55 ERROR]: [ACF]         at co.aikar.commands.BukkitRootCommand.execute(BukkitRootCommand.java:81)
[02:26:55 ERROR]: [ACF]         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[02:26:55 ERROR]: [ACF]         at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[02:26:55 ERROR]: [ACF]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[02:26:55 ERROR]: [ACF]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[02:26:55 ERROR]: [ACF]         at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[02:26:55 ERROR]: [ACF]         at java.base/java.lang.Thread.run(Thread.java:830)
[02:26:55 ERROR]: [ACF] Caused by: java.lang.NoClassDefFoundError: org/bukkit/Nameable
[02:26:55 ERROR]: [ACF]         at de.themoep.inventorygui.InventoryGui.replaceVars(InventoryGui.java:1271)
[02:26:55 ERROR]: [ACF]         at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:573)
[02:26:55 ERROR]: [ACF]         at de.themoep.inventorygui.InventoryGui.draw(InventoryGui.java:556)
[02:26:55 ERROR]: [ACF]         at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:499)
[02:26:55 ERROR]: [ACF]         at de.themoep.inventorygui.InventoryGui.show(InventoryGui.java:490)
```

What is the version compatibility? I don't see it mentioned anywhere on the docs. It did not work on `1.8.8`

**Comment by Phoenix616** [comment]
Well technically it's only guaranteed to work with the [version which is depended](https://github.com/Phoenix616/InventoryGui/blob/master/pom.xml#L30) on (and ones beyond that) but when issues occur with older versions then I'm open to fixing them if that is possible in an easy and justifiable way.

Providing full support for software that is [over five years old](https://howoldisminecraft188.today/) isn't really viable for me though due to it missing tons of features as well as having massive security issues. I personally would advice anyone to upgrade to a more modern version of Minecraft as soon as possible.
